name: Maintain a language
description: Request to become a maintainer
title: "maintain: "
labels: []
body:
  - type: input
    id: language
    attributes:
      label: What language do you want to maintain?
    validations:
      required: true
