name: Automate Translations

on:
  push:
    paths:
      - "en.json"
      - "*.ts"
  workflow_dispatch:

jobs:
  auto:
    runs-on: ubuntu-latest
    name: "Automate Translations"

    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Run Files
        run: deno run --allow-read --allow-write *.ts
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          add: "*.json"
          message: "Update Automatic Languages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
